[tool.poetry]
name = "greenhack"
version = "0.1.0"
description = ""
authors = ["pwtail <abvit89s@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
greenlet = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
